# PlayStation wireless controller
# Deadman (enable) button: Right Trigger
teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: xbox_vel_raw
    deadman_buttons: [0]
    axis_mappings:
      -
        axis: 2  # Right thumb stick (up/down)
        target: linear.x
        scale: -10.0
        offset: 0.0
      -
        axis: 1  # Right thumb stick (left/right)
        target: linear.y
        scale: 10.0
        offset: 0.0
      -
        axis: 0  # Left thumb stick (up/down)
        target: linear.z
        scale: -10.0
        offset: 0.0
      -
        axis: 3  # Left thumb stick (left/right)
        target: angular.z
        scale: 10.0
        offset: 0.0
  takeoff:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: takeoff
    deadman_buttons: [1]  # RT + Y 
    axis_mappings: []
  land:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: land
    deadman_buttons: [1, 7]  # RT + A
    axis_mappings: []
  emergency:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: reset
    deadman_buttons: [2, 7] # RT + B
    axis_mappings: []
  flattrim:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: flattrim
    deadman_buttons: [0, 7] # RT + X
    axis_mappings: []
  moveItCancel:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: moveIt/Cancel
    deadman_buttons: [1] # 
    axis_mappings: []
  snapshot:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: snapshot
    deadman_buttons: [7, 4] # RT + LB
    axis_mappings: []
  cancel_land:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: force_enable_landing
    deadman_buttons: [7, 5] # RT + LB
    axis_mappings: []
  force_land:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: cancel_landing
    deadman_buttons: [4, 6] # RT + LB
    axis_mappings: []
  pid_enable:
    type: topic
    message_type: "std_msgs/Bool"
    topic_name: pid_enable
    deadman_buttons: [5, 4] # RT + LB
    axis_mappings: []
    message_value:
      -
        target: data
        value: true
  
