# Xbox 360 wireless controller
# Deadman (enable) button: Right Bumper
teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: xbox_vel_raw
    deadman_buttons: [7]
    axis_mappings:
      -
        axis: 3  # Right thumb stick (up/down)
        target: linear.x
        scale: 1.0
        offset: 0.0
      -
        axis: 2  # Right thumb stick (left/right)
        target: linear.y
        scale: 1.0
        offset: 0.0
      -
        axis: 1  # Left thumb stick (up/down)
        target: linear.z
        scale: 1.0
        offset: 0.0
      -
        axis: 0  # Left thumb stick (left/right)
        target: angular.z
        scale: 1.0
        offset: 0.0
